"use client";

import { useState } from "react";
import { AlertTriangle, Bell, CalendarDays, Check, ChevronDown, Clock, CreditCard, ExternalLink, Gift, ImagePlus, Link2, LockKeyhole, LogOut, MapPin, Plus, Save, Settings2, ShieldCheck, Store, Trash2, Truck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import { AdminSettings, BusinessDay, HolidayClosure, SettingsSection, saveAdminSettings, signOutStaffSession, updateAdminPassword } from "@/lib/admin-settings";

type Errors = Partial<Record<"name" | "email" | "phone" | "hours", string>>;
const sections: { id: SettingsSection; label: string; icon: typeof Store }[] = [
  { id: "profile", label: "Store Profile", icon: Store }, { id: "hours", label: "Hours & Times", icon: Clock }, { id: "holidays", label: "Holiday Closures", icon: CalendarDays }, { id: "checkout", label: "Checkout & Delivery", icon: Truck }, { id: "payment", label: "Payment Methods", icon: CreditCard }, { id: "notifications", label: "Notifications", icon: Bell }, { id: "integrations", label: "Integrations", icon: Link2 }, { id: "security", label: "Security & Sessions", icon: LockKeyhole },
];

export function SettingsContent({ initialSettings }: { initialSettings: AdminSettings }) {
  const [settings, setSettings] = useState(initialSettings);
  const [activeSection, setActiveSection] = useState<SettingsSection>("profile");
  const [errors, setErrors] = useState<Errors>({});
  const [busy, setBusy] = useState(false);
  const [holidayOpen, setHolidayOpen] = useState(false);
  const [sessionTarget, setSessionTarget] = useState<string | null>(null);
  const [passwords, setPasswords] = useState({ current: "", next: "" });
  const [holiday, setHoliday] = useState({ name: "", date: "" });
  const [original, setOriginal] = useState(() => JSON.stringify(initialSettings));
  const dirty = JSON.stringify(settings) !== original;

  const validate = () => {
    const next: Errors = {};
    if (!settings.profile.name.trim()) next.name = "Store name is required.";
    if (!/^\S+@\S+\.\S+$/.test(settings.profile.email)) next.email = "Enter a valid support email address.";
    if (!/^\+?[\d ()-]{10,}$/.test(settings.profile.phone)) next.phone = "Enter a valid phone number including country code.";
    if (settings.hours.some((day) => day.open && day.opensAt >= day.closesAt)) next.hours = "Closing time must be later than opening time.";
    setErrors(next);
    if (Object.keys(next).length) { document.getElementById("settings-errors")?.scrollIntoView({ behavior: "smooth" }); return false; }
    return true;
  };

  const save = async () => {
    if (!validate()) { toast.error("Review the highlighted settings before saving."); return; }
    setBusy(true);
    try { await saveAdminSettings(settings); setOriginal(JSON.stringify(settings)); toast.success("Settings saved successfully — atelier preferences are now live."); } catch { toast.error("Unable to save studio settings."); } finally { setBusy(false); }
  };

  const discard = () => { setSettings(JSON.parse(original) as AdminSettings); setErrors({}); toast.info("Unsaved settings discarded."); };
  const navigate = (id: SettingsSection) => { setActiveSection(id); document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const updateProfile = (key: keyof AdminSettings["profile"], value: string) => setSettings((current) => ({ ...current, profile: { ...current.profile, [key]: value } }));
  const updateDay = (index: number, update: Partial<BusinessDay>) => setSettings((current) => ({ ...current, hours: current.hours.map((day, itemIndex) => itemIndex === index ? { ...day, ...update } : day) }));
  const addHoliday = () => { if (!holiday.name || !holiday.date) return; const item: HolidayClosure = { id: `holiday-${Date.now()}`, name: holiday.name, date: holiday.date, closed: true }; setSettings((current) => ({ ...current, holidays: [...current.holidays, item] })); setHoliday({ name: "", date: "" }); setHolidayOpen(false); toast.success("Holiday closure added."); };
  const removeHoliday = (id: string) => setSettings((current) => ({ ...current, holidays: current.holidays.filter((item) => item.id !== id) }));
  const toggleCheckout = (key: keyof AdminSettings["checkout"]) => setSettings((current) => ({ ...current, checkout: { ...current.checkout, [key]: !current.checkout[key] } }));
  const toggleNotification = (key: keyof AdminSettings["notifications"]) => setSettings((current) => ({ ...current, notifications: { ...current.notifications, [key]: !current.notifications[key] } }));
  const toggleIntegration = (id: string) => setSettings((current) => ({ ...current, integrations: current.integrations.map((item) => item.id === id ? { ...item, connected: !item.connected } : item) }));
  const signOut = async () => { if (!sessionTarget) return; setBusy(true); try { await signOutStaffSession(sessionTarget); setSettings((current) => ({ ...current, sessions: current.sessions.filter((item) => item.id !== sessionTarget) })); setSessionTarget(null); toast.success("Staff session signed out."); } catch { toast.error("Could not sign out session."); } finally { setBusy(false); } };
  const updatePassword = async () => { if (!passwords.current || passwords.next.length < 12) { toast.error("Enter your current password and a new password of at least 12 characters."); return; } setBusy(true); try { await updateAdminPassword(); setPasswords({ current: "", next: "" }); toast.success("Password updated successfully."); } catch { toast.error("Could not update password."); } finally { setBusy(false); } };

  return <div className="mx-auto max-w-[1440px] space-y-6 px-5 py-6 lg:px-16 lg:py-10">
    {Object.keys(errors).length > 0 && <div id="settings-errors" role="alert" className="flex items-start gap-4 rounded-2xl bg-error-container p-4 text-error"><AlertTriangle className="mt-0.5 h-6 w-6 shrink-0" /><div className="flex-1"><h2 className="font-serif text-xl">Unable to save studio settings</h2><p className="text-sm">{Object.keys(errors).length} validation issues require attention.</p></div><Button variant="destructive" onClick={save}>Retry Save</Button></div>}
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-secondary">Atelier architecture · Live store</p><h1 className="mt-2 font-serif text-4xl">Settings</h1><p className="mt-1 text-on-surface-variant">Configure store identity, operating hours, checkout preferences, and security.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-secondary-container px-4 py-2 text-xs font-medium text-on-secondary-container"><span className="h-2 w-2 rounded-full bg-secondary" /> Healthy sync active</span></header>
    <div className="lg:hidden"><label className="relative block"><span className="sr-only">Settings section</span><select value={activeSection} onChange={(event) => navigate(event.target.value as SettingsSection)} className="min-h-12 w-full appearance-none rounded-full border border-outline-variant bg-surface-container-lowest px-4 pr-10">{sections.map((section) => <option key={section.id} value={section.id}>{section.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2" /></label></div>
    <div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="hidden lg:block"><nav className="sticky top-24 space-y-1 rounded-2xl bg-surface-container p-2" aria-label="Settings sections">{sections.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => navigate(id)} className={cn("flex min-h-11 w-full items-center gap-3 rounded-full px-4 text-left text-sm transition-colors", activeSection === id ? "bg-primary-container font-medium text-on-primary-container" : "text-on-surface-variant hover:bg-surface-container-high")}><Icon className="h-4 w-4" />{label}{errors[id === "profile" ? "email" : id === "hours" ? "hours" : "name"] && <span className="ml-auto h-2 w-2 rounded-full bg-error" />}</button>)}</nav></aside>
      <main className="space-y-6">
        <SettingsCard id="profile" icon={Store} eyebrow="Identity & location" title="Store Profile" subtitle="Public brand details and customer-facing contact information."><div className="rounded-xl bg-surface-container p-4"><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-xl bg-secondary-container text-secondary"><Store className="h-7 w-7" /></span><div className="flex-1"><p className="font-medium">Bloom &amp; Stem Atelier Emblem</p><p className="text-xs text-on-surface-variant">SVG or PNG · maximum 2MB</p></div><Button variant="outline" size="sm"><ImagePlus className="h-4 w-4" /> Replace Logo</Button></div></div><div className="grid gap-4 md:grid-cols-2"><Field id="store-name" label="Store Name" error={errors.name}><Input id="store-name" value={settings.profile.name} onChange={(event) => updateProfile("name", event.target.value)} aria-invalid={!!errors.name} className="min-h-11 rounded-xl bg-surface-container" /></Field><Field id="store-email" label="Support & Concierge Email" error={errors.email}><Input id="store-email" type="email" value={settings.profile.email} onChange={(event) => updateProfile("email", event.target.value)} aria-invalid={!!errors.email} className="min-h-11 rounded-xl bg-surface-container" /></Field><Field id="store-phone" label="Direct Atelier Telephone" error={errors.phone}><Input id="store-phone" value={settings.profile.phone} onChange={(event) => updateProfile("phone", event.target.value)} aria-invalid={!!errors.phone} className="min-h-11 rounded-xl bg-surface-container" /></Field><Field id="store-address" label="Atelier Physical Address"><Input id="store-address" value={settings.profile.address} onChange={(event) => updateProfile("address", event.target.value)} className="min-h-11 rounded-xl bg-surface-container" /></Field></div><Field id="store-tagline" label="Public Tagline"><Textarea id="store-tagline" value={settings.profile.tagline} onChange={(event) => updateProfile("tagline", event.target.value)} className="rounded-xl bg-surface-container" /></Field></SettingsCard>

        <SettingsCard id="hours" icon={Clock} eyebrow="Availability schedules" title="Studio Operating Hours" subtitle="Regular pickup, arrangement, and delivery windows."><div className="flex justify-end"><Button variant="ghost" size="sm" onClick={() => setSettings((current) => ({ ...current, hours: current.hours.map((day, index) => index > 0 && index < 5 ? { ...day, open: current.hours[0].open, opensAt: current.hours[0].opensAt, closesAt: current.hours[0].closesAt } : day) }))}>Apply Monday to weekdays</Button></div>{errors.hours && <p className="rounded-xl bg-error-container p-3 text-sm text-error">{errors.hours}</p>}<div className="space-y-2">{settings.hours.map((day, index) => <div key={day.day} className={cn("grid gap-3 rounded-xl bg-surface-container p-3 sm:grid-cols-[130px_1fr_1fr_auto] sm:items-center", day.open && day.opensAt >= day.closesAt && "bg-error-container")}><span className="font-medium">{day.day}</span><label className="text-xs text-on-surface-variant">Opens<Input type="time" disabled={!day.open} value={day.opensAt} onChange={(event) => updateDay(index, { opensAt: event.target.value })} className="mt-1 min-h-11 rounded-full bg-surface-container-lowest" /></label><label className="text-xs text-on-surface-variant">Closes<Input type="time" disabled={!day.open} value={day.closesAt} onChange={(event) => updateDay(index, { closesAt: event.target.value })} className="mt-1 min-h-11 rounded-full bg-surface-container-lowest" /></label><Toggle checked={day.open} onChange={() => updateDay(index, { open: !day.open })} label={`${day.day} ${day.open ? "open" : "closed"}`} /></div>)}</div></SettingsCard>

        <SettingsCard id="holidays" icon={CalendarDays} eyebrow="Exceptions" title="Special Closures & Botanical Holidays" subtitle="Seasonal closures and extended operating hours."><div className="flex justify-end"><Button size="sm" onClick={() => setHolidayOpen(true)}><Plus className="h-4 w-4" /> Add Holiday</Button></div><div className="space-y-3">{settings.holidays.map((item) => <div key={item.id} className="flex items-center gap-4 rounded-xl bg-surface-container p-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-primary-fixed text-xs font-medium text-primary">{new Date(`${item.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</span><div className="flex-1"><p className="font-medium">{item.name}</p><p className="text-xs text-on-surface-variant">{item.closed ? "Atelier closed" : item.hours}</p></div><span className={cn("rounded-full px-3 py-1 text-xs", item.closed ? "bg-error-container text-error" : "bg-secondary-container text-on-secondary-container")}>{item.closed ? "Closed" : "Custom hours"}</span><button onClick={() => removeHoliday(item.id)} aria-label={`Remove ${item.name}`} className="grid h-11 w-11 place-items-center rounded-full text-error hover:bg-error-container"><Trash2 className="h-4 w-4" /></button></div>)}</div></SettingsCard>

        <SettingsCard id="checkout" icon={Truck} eyebrow="Client journey" title="Checkout & Delivery Experience" subtitle="Configure customer-facing gift and delivery options."><div className="grid gap-3 md:grid-cols-2"><SettingToggle title="Guest Checkout" text="Allow purchases without account registration." checked={settings.checkout.guestCheckout} onChange={() => toggleCheckout("guestCheckout")} /><SettingToggle title="Gift Options & Calligraphy" text="Offer handwritten cards and gift enclosures." checked={settings.checkout.giftOptions} onChange={() => toggleCheckout("giftOptions")} /><SettingToggle title="Cold-Chain Delivery Picker" text="Let clients select temperature-safe delivery slots." checked={settings.checkout.deliveryDatePicker} onChange={() => toggleCheckout("deliveryDatePicker")} /><SettingToggle title="Florist Arrangement Notes" text="Allow special design and handling requests." checked={settings.checkout.arrangementNotes} onChange={() => toggleCheckout("arrangementNotes")} /></div></SettingsCard>

        <SettingsCard id="payment" icon={CreditCard} eyebrow="Financial gateways" title="Payment Infrastructure" subtitle="Manage connected merchant accounts and test environments."><div className="flex flex-col gap-4 rounded-xl bg-surface-container p-4 sm:flex-row sm:items-center"><span className="grid h-12 w-12 place-items-center rounded-xl bg-surface-container-high"><CreditCard className="h-5 w-5" /></span><div className="flex-1"><p className="font-serif text-xl">{settings.payment.provider}</p><p className="text-xs text-on-surface-variant">Merchant account ending 8842</p></div><span className="rounded-full bg-secondary-container px-3 py-1 text-xs text-on-secondary-container"><Check className="mr-1 inline h-3 w-3" /> Connected</span><SettingToggle compact title="Test mode" text="Sandbox transactions" checked={settings.payment.testMode} onChange={() => setSettings((current) => ({ ...current, payment: { ...current.payment, testMode: !current.payment.testMode } }))} /></div></SettingsCard>

        <SettingsCard id="notifications" icon={Bell} eyebrow="Atelier telemetry" title="Automated Notifications" subtitle="Manage operational email, stock, customer, and digest alerts."><div className="space-y-3"><SettingToggle title="Order Confirmation & Floral Care Guide" text="Notify staff when orders are successfully paid." checked={settings.notifications.orderConfirmation} onChange={() => toggleNotification("orderConfirmation")} /><SettingToggle title="Cold-Room Low-Stock Alerts" text="Warn florists when inventory reaches its threshold." checked={settings.notifications.lowStock} onChange={() => toggleNotification("lowStock")} /><SettingToggle title="VIP Client Created" text="Notify the liaison when a high-value profile appears." checked={settings.notifications.vipCustomer} onChange={() => toggleNotification("vipCustomer")} /><SettingToggle title="Weekly Atelier Analytics Digest" text="Send sales, seasonal demand, and inventory insights." checked={settings.notifications.weeklyDigest} onChange={() => toggleNotification("weeklyDigest")} /></div></SettingsCard>

        <SettingsCard id="integrations" icon={Link2} eyebrow="External ecosystem" title="Integrations" subtitle="Connect logistics, marketing automation, and analytics providers."><div className="grid gap-4 md:grid-cols-3">{settings.integrations.map((integration) => <article key={integration.id} className="flex flex-col rounded-xl bg-surface-container p-4"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-secondary-container text-secondary"><Link2 className="h-4 w-4" /></span><span className={cn("rounded-full px-2 py-1 text-[11px]", integration.connected ? "bg-secondary-container text-on-secondary-container" : "bg-surface-container-high text-on-surface-variant")}>{integration.connected ? "Connected" : "Disconnected"}</span></div><h3 className="mt-4 font-medium">{integration.name}</h3><p className="mt-1 flex-1 text-xs leading-5 text-on-surface-variant">{integration.description}</p><Button variant={integration.connected ? "ghost" : "outline"} size="sm" onClick={() => toggleIntegration(integration.id)} className={cn("mt-4", integration.connected && "text-error")}>{integration.connected ? "Disconnect" : "Connect integration"}</Button></article>)}</div></SettingsCard>

        <SettingsCard id="security" icon={LockKeyhole} eyebrow="Protection & access" title="Security & Staff Sessions" subtitle="Review active devices and update administrative credentials."><div className="space-y-3"><h3 className="font-medium">Authenticated Devices</h3>{settings.sessions.map((session) => <div key={session.id} className="flex items-center gap-3 rounded-xl bg-surface-container p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-secondary-container text-secondary"><ShieldCheck className="h-4 w-4" /></span><div className="flex-1"><p className="font-medium">{session.device} {session.current && <span className="ml-2 rounded-full bg-secondary-container px-2 py-0.5 text-[11px] text-on-secondary-container">This device</span>}</p><p className="text-xs text-on-surface-variant">{session.location} · {session.lastActive}</p></div>{!session.current && <Button variant="outline" size="sm" onClick={() => setSessionTarget(session.id)}><LogOut className="h-4 w-4" /> Sign Out</Button>}</div>)}</div><div className="mt-6 border-t border-outline-variant/30 pt-6"><h3 className="font-medium">Update Admin Password</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field id="current-password" label="Current Password"><Input id="current-password" type="password" value={passwords.current} onChange={(event) => setPasswords((current) => ({ ...current, current: event.target.value }))} className="min-h-11 rounded-xl bg-surface-container" /></Field><Field id="new-password" label="New Password"><Input id="new-password" type="password" value={passwords.next} onChange={(event) => setPasswords((current) => ({ ...current, next: event.target.value }))} placeholder="At least 12 characters" className="min-h-11 rounded-xl bg-surface-container" /></Field></div><Button variant="outline" onClick={updatePassword} disabled={busy} className="mt-4">Update Password</Button></div></SettingsCard>
      </main>
    </div>
    <div className="sticky bottom-4 z-20 flex flex-col gap-3 rounded-2xl bg-surface-container-high p-4 shadow-lg sm:flex-row sm:items-center"><div className="flex-1"><p className="font-medium">{dirty ? "Unsaved changes" : "All settings saved"}</p><p className="text-xs text-on-surface-variant">Changes publish to the live storefront after validation.</p></div><Button variant="ghost" disabled={!dirty || busy} onClick={discard}>Discard</Button><Button disabled={!dirty || busy} onClick={save}><Save className="h-4 w-4" /> Save Changes</Button></div>

    <Dialog open={holidayOpen} onOpenChange={setHolidayOpen}><DialogContent style={{ width: "min(32rem, calc(100vw - 2rem))", maxWidth: "none" }} className="rounded-2xl bg-white p-6"><DialogHeader><DialogTitle className="font-serif text-2xl">Add Holiday Closure</DialogTitle><DialogDescription>Add a full closure or seasonal operating exception.</DialogDescription></DialogHeader><div className="space-y-4"><Field id="holiday-name" label="Closure name"><Input id="holiday-name" value={holiday.name} onChange={(event) => setHoliday((current) => ({ ...current, name: event.target.value }))} /></Field><Field id="holiday-date" label="Date"><Input id="holiday-date" type="date" value={holiday.date} onChange={(event) => setHoliday((current) => ({ ...current, date: event.target.value }))} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setHolidayOpen(false)}>Cancel</Button><Button disabled={!holiday.name || !holiday.date} onClick={addHoliday}>Add Closure</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!sessionTarget} onOpenChange={(open) => !open && setSessionTarget(null)}><DialogContent style={{ width: "min(30rem, calc(100vw - 2rem))", maxWidth: "none" }} className="rounded-2xl bg-white p-6"><DialogHeader><DialogTitle className="font-serif text-2xl">Sign out staff session?</DialogTitle><DialogDescription>The device will immediately lose access and must authenticate again.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setSessionTarget(null)}>Cancel</Button><Button variant="destructive" disabled={busy} onClick={signOut}>Sign Out Session</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function SettingsCard({ id, icon: Icon, eyebrow, title, subtitle, children }: { id: SettingsSection; icon: typeof Store; eyebrow: string; title: string; subtitle: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-24 rounded-2xl bg-surface-container-lowest p-5 shadow-sm sm:p-6"><header className="mb-5 flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-secondary-container text-secondary"><Icon className="h-5 w-5" /></span><div><p className="text-[11px] font-medium uppercase tracking-widest text-primary">{eyebrow}</p><h2 className="font-serif text-2xl">{title}</h2><p className="text-sm text-on-surface-variant">{subtitle}</p></div></header><div className="space-y-4">{children}</div></section>; }
function Field({ id, label, error, children }: { id: string; label: string; error?: string; children: React.ReactNode }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}{error && <p id={`${id}-error`} className="text-xs font-medium text-error">{error}</p>}</div>; }
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) { return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={onChange} className={cn("relative h-7 w-12 shrink-0 rounded-full transition-colors", checked ? "bg-secondary" : "bg-surface-container-highest")}><span className={cn("absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition-transform motion-reduce:transition-none", checked ? "left-6" : "left-1")} /></button>; }
function SettingToggle({ title, text, checked, onChange, compact }: { title: string; text: string; checked: boolean; onChange: () => void; compact?: boolean }) { return <div className={cn("flex items-center gap-4 rounded-xl bg-surface-container p-4", compact && "bg-transparent p-0")}><div className="flex-1"><p className="text-sm font-medium">{title}</p><p className="text-xs text-on-surface-variant">{text}</p></div><Toggle checked={checked} onChange={onChange} label={title} /></div>; }
