import { AlertTriangle, MailOpen, SearchX, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

export function NewsletterSkeleton() { return <div className="mx-auto max-w-[1440px] space-y-6 px-5 py-6 lg:px-16 lg:py-10" aria-label="Loading newsletter workspace" aria-busy="true"><div className="flex justify-between"><div className="space-y-3"><Skeleton className="h-10 w-72" /><Skeleton className="h-5 w-96 max-w-full" /></div><Skeleton className="hidden h-12 w-44 rounded-full sm:block" /></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-28 rounded-2xl" />)}</div><Skeleton className="h-48 rounded-2xl" /><Skeleton className="h-[480px] rounded-2xl" /></div>; }
export function NewsletterError({ onRetry }: { onRetry: () => void }) { return <div className="mx-auto flex min-h-[60vh] max-w-xl flex-col items-center justify-center px-5 text-center"><div className="mb-5 grid h-20 w-20 place-items-center rounded-full bg-error-container text-error"><AlertTriangle className="h-9 w-9" /></div><h1 className="font-serif text-3xl">Could not load newsletter workspace</h1><p className="mt-2 text-on-surface-variant">Campaign and subscriber data are temporarily unavailable. Scheduled broadcasts remain unchanged.</p><Button onClick={onRetry} className="mt-6 min-h-11 rounded-full px-6">Retry connection</Button></div>; }
export function CampaignsEmpty({ onCreate }: { onCreate: () => void }) { return <div className="rounded-2xl bg-surface-container-lowest px-5 py-14 text-center"><MailOpen className="mx-auto h-10 w-10 text-secondary" /><h2 className="mt-4 font-serif text-2xl">No campaigns in this view</h2><p className="mt-2 text-on-surface-variant">Compose a botanical dispatch or select a different campaign status.</p><Button onClick={onCreate} className="mt-5">Create Campaign</Button></div>; }
export function SubscribersEmpty({ onCreate }: { onCreate: () => void }) { return <div className="mx-auto flex min-h-[40vh] max-w-xl flex-col items-center justify-center rounded-2xl bg-surface-container-lowest px-5 py-14 text-center"><Users className="mx-auto h-10 w-10 text-secondary" /><h2 className="mt-4 font-serif text-2xl">No subscribers yet</h2><p className="mt-2 text-on-surface-variant">Your mailing list is empty. Start growing it with an embedded signup form or your first campaign.</p><Button onClick={onCreate} className="mt-5">Create Campaign</Button></div>; }
export function SubscribersNoResults({ onClear }: { onClear: () => void }) { return <div className="mx-auto flex min-h-[40vh] max-w-xl flex-col items-center justify-center rounded-2xl bg-surface-container-lowest px-5 py-14 text-center"><SearchX className="mx-auto h-10 w-10 text-secondary" /><h2 className="mt-4 font-serif text-2xl">No subscribers match</h2><p className="mt-2 text-on-surface-variant">Try a different search term or segment filter to find subscribers.</p><Button onClick={onClear} className="mt-5">Clear filters</Button></div>; }
