"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { Archive, Check, Copy, Edit3, Filter, Grid2X2, List, PackagePlus, Search, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Product } from "@/types";
import { mutateAdminProducts } from "@/lib/admin-products";
import { cn } from "@/lib/utils";
import { ProductsEmpty, ProductsNoResults } from "./states";

type StockFilter="all"|"in"|"low"|"out";
type Availability="all"|"available"|"hidden";
const images=["/product-detail/bouquet-main.png","/product-detail/lifestyle.png","/product-detail/packaging.png","/product-detail/peony-detail.png"];
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export function ProductsContent({initialProducts}:{initialProducts:Product[]}) {
 const [products,setProducts]=useState(initialProducts);
 const [search,setSearch]=useState("");
 const [category,setCategory]=useState("all");
 const [stock,setStock]=useState<StockFilter>("all");
 const [availability,setAvailability]=useState<Availability>("all");
 const [filtersOpen,setFiltersOpen]=useState(false);
 const [view,setView]=useState<"table"|"grid">("table");
 const [selected,setSelected]=useState<Set<string>>(new Set());
 const [editing,setEditing]=useState<Product|null>(null);
 const [archiving,setArchiving]=useState<Product|null>(null);
 const [busy,setBusy]=useState(false);
 const categories=useMemo(()=>Array.from(new Set(products.map(p=>p.category?.name).filter(Boolean))) as string[],[products]);
 const filtered=useMemo(()=>products.filter(p=>{const q=search.trim().toLowerCase(); const threshold=p.lowStockThreshold??5; return (!q||`${p.name} ${p.sku} ${p.category?.name??""}`.toLowerCase().includes(q))&&(category==="all"||p.category?.name===category)&&(availability==="all"||(availability==="available")===p.isActive)&&(stock==="all"||(stock==="in"&&p.stock>threshold)||(stock==="low"&&p.stock>0&&p.stock<=threshold)||(stock==="out"&&p.stock===0));}),[products,search,category,stock,availability]);
 const clear=()=>{setSearch("");setCategory("all");setStock("all");setAvailability("all")};
 const run=async(action:Parameters<typeof mutateAdminProducts>[0],success:string,change:()=>void)=>{setBusy(true);try{await mutateAdminProducts(action);change();toast.success(success)}catch{toast.error("That change could not be saved. Please try again.")}finally{setBusy(false)}};
 const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
 const setBulk=(active:boolean)=>run("availability",`${selected.size} products ${active?"published":"hidden"}.`,()=>{setProducts(ps=>ps.map(p=>selected.has(p.id)?{...p,isActive:active}:p));setSelected(new Set())});
 if(!products.length)return <ProductsEmpty onAction={()=>toast.info("Product creation is coming soon.")}/>;
 if(!filtered.length)return <ProductsNoResults onAction={clear}/>;
 return <div className="mx-auto max-w-[1440px] space-y-6 px-5 py-6 lg:px-16 lg:py-10">
  <header className="flex items-center justify-between gap-4"><div><h1 className="font-serif text-3xl text-on-surface lg:text-4xl">Products <span className="ml-1 text-xl font-normal text-on-surface-variant">({products.length})</span></h1><p className="mt-1 hidden text-sm text-on-surface-variant sm:block">Manage your botanical inventory, pricing, and availability.</p></div><Button onClick={()=>toast.info("Product creation is coming soon.")} className="min-h-11 rounded-full px-5"><PackagePlus className="h-5 w-5"/><span className="hidden sm:inline">Add Product</span></Button></header>
  <section className="flex flex-col gap-3 rounded-2xl bg-surface-container p-2 shadow-sm lg:flex-row lg:items-center"><label className="relative flex-1"><span className="sr-only">Search products</span><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-outline"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, SKU, or category..." className="min-h-11 rounded-full border-0 bg-surface-container-lowest pl-11"/></label><div className="flex items-center justify-between gap-2"><Button variant="outline" onClick={()=>setFiltersOpen(true)} className="min-h-11 rounded-full"><Filter className="h-4 w-4"/>Filters{[category!=="all",stock!=="all",availability!=="all"].filter(Boolean).length>0&&<span className="rounded-full bg-primary px-2 text-xs text-on-primary">{[category!=="all",stock!=="all",availability!=="all"].filter(Boolean).length}</span>}</Button><div className="flex rounded-full bg-surface-container-lowest p-1" aria-label="View options"><button aria-label="Table view" aria-pressed={view==="table"} onClick={()=>setView("table")} className={cn("min-h-10 min-w-10 rounded-full grid place-items-center",view==="table"&&"bg-surface-container-high")}><List className="h-5 w-5"/></button><button aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>setView("grid")} className={cn("min-h-10 min-w-10 rounded-full grid place-items-center",view==="grid"&&"bg-surface-container-high")}><Grid2X2 className="h-5 w-5"/></button></div></div></section>
  {selected.size>0&&<div className="flex flex-wrap items-center gap-3 rounded-2xl bg-inverse-surface px-5 py-3 text-inverse-on-surface" role="status"><span className="mr-auto font-medium">{selected.size} selected</span><Button disabled={busy} variant="outline" onClick={()=>setBulk(true)} className="min-h-11 rounded-full bg-transparent text-inverse-on-surface">Make available</Button><Button disabled={busy} variant="outline" onClick={()=>setBulk(false)} className="min-h-11 rounded-full bg-transparent text-inverse-on-surface">Hide products</Button></div>}
  {view==="table"?<div className="hidden overflow-hidden rounded-2xl bg-surface-container-lowest shadow-sm md:block"><table className="w-full text-left"><thead className="border-b border-outline-variant bg-surface-container-low text-xs text-on-surface-variant"><tr><th className="p-4"><input aria-label="Select all visible products" type="checkbox" checked={selected.size===filtered.length} onChange={()=>setSelected(selected.size===filtered.length?new Set():new Set(filtered.map(p=>p.id)))} className="h-5 w-5 accent-secondary"/></th><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4 text-right">Price</th><th className="p-4 text-right">Inventory</th><th className="p-4 text-center">Available</th><th className="p-4"><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map((p,i)=><ProductRow key={p.id} product={p} image={images[i%images.length]} selected={selected.has(p.id)} onSelect={()=>toggle(p.id)} onAvailability={()=>run("availability",`${p.name} is now ${p.isActive?"hidden":"available"}.`,()=>setProducts(ps=>ps.map(x=>x.id===p.id?{...x,isActive:!x.isActive}:x)))} onEdit={()=>setEditing(p)} onDuplicate={()=>run("duplicate",`${p.name} duplicated.`,()=>setProducts(ps=>[...ps,{...p,id:`${p.id}-copy-${Date.now()}`,name:`${p.name} copy`,sku:`${p.sku}-COPY`}]))} onArchive={()=>setArchiving(p)}/>)}</tbody></table></div>:<ProductGrid products={filtered} selected={selected} onSelect={toggle} onEdit={setEditing}/>}
  <div className={cn(view==="table"?"grid gap-3 md:hidden":"hidden")}>{filtered.map((p,i)=><ProductCard key={p.id} product={p} image={images[i%images.length]} selected={selected.has(p.id)} onSelect={()=>toggle(p.id)} onEdit={()=>setEditing(p)} onAvailability={()=>run("availability","Availability updated.",()=>setProducts(ps=>ps.map(x=>x.id===p.id?{...x,isActive:!x.isActive}:x)))}/>)}</div>
  <Filters open={filtersOpen} setOpen={setFiltersOpen} categories={categories} category={category} setCategory={setCategory} stock={stock} setStock={setStock} availability={availability} setAvailability={setAvailability} clear={clear}/>
  <EditDialog product={editing} setProduct={setEditing} busy={busy} save={(draft)=>run("update",`${draft.name} updated.`,()=>{setProducts(ps=>ps.map(p=>p.id===draft.id?draft:p));setEditing(null)})}/>
  <Dialog open={!!archiving} onOpenChange={o=>!o&&setArchiving(null)}><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Archive product?</DialogTitle><DialogDescription>{archiving?.name} will be hidden from customers. You can restore it later.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setArchiving(null)}>Cancel</Button><Button disabled={busy} variant="destructive" onClick={()=>archiving&&run("archive",`${archiving.name} archived.`,()=>{setProducts(ps=>ps.filter(p=>p.id!==archiving.id));setArchiving(null)})}><Archive/>Archive</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}

function ProductRow({product,image,selected,onSelect,onAvailability,onEdit,onDuplicate,onArchive}:{product:Product;image:string;selected:boolean;onSelect:()=>void;onAvailability:()=>void;onEdit:()=>void;onDuplicate:()=>void;onArchive:()=>void}){return <tr className="group border-b border-outline-variant/40 hover:bg-surface-container-low/50"><td className="p-4"><input aria-label={`Select ${product.name}`} type="checkbox" checked={selected} onChange={onSelect} className="h-5 w-5 accent-secondary"/></td><td className="p-4"><div className="flex items-center gap-4"><Image src={image} alt="" width={48} height={64} className="h-16 w-12 rounded-lg object-cover"/><div><div className="font-serif text-lg">{product.name}{product.isBestSeller&&<span className="ml-2 rounded-full bg-secondary-container px-2 py-1 font-sans text-[10px] uppercase text-on-secondary-container">Bestseller</span>}</div><div className="font-mono text-xs text-on-surface-variant">SKU: {product.sku}</div></div></div></td><td className="p-4 text-sm">{product.category?.name??"Uncategorized"}</td><td className="p-4 text-right font-medium">{money.format(product.salePrice??product.price)}</td><td className="p-4 text-right"><Stock product={product}/></td><td className="p-4 text-center"><Switch checked={product.isActive} label={`${product.name} availability`} onClick={onAvailability}/></td><td className="p-4"><div className="flex justify-end opacity-100 lg:opacity-0 lg:group-hover:opacity-100"><Action label="Quick edit" onClick={onEdit}><Edit3/></Action><Action label="Duplicate" onClick={onDuplicate}><Copy/></Action><Action label="Archive" onClick={onArchive} destructive><Archive/></Action></div></td></tr>}
function ProductCard({product,image,selected,onSelect,onEdit,onAvailability}:{product:Product;image:string;selected:boolean;onSelect:()=>void;onEdit:()=>void;onAvailability:()=>void}){return <article className="relative flex items-center gap-4 rounded-2xl bg-surface-container-lowest p-2 pr-3 shadow-sm"><button onClick={onSelect} aria-label={`${selected?"Deselect":"Select"} ${product.name}`} className={cn("absolute left-3 top-3 z-10 grid h-6 w-6 place-items-center rounded-md border bg-white",selected&&"bg-secondary text-on-secondary")} >{selected&&<Check className="h-4 w-4"/>}</button><Image src={image} alt="" width={80} height={80} className="h-20 w-20 shrink-0 rounded-xl object-cover"/><button onClick={onEdit} className="min-w-0 flex-1 text-left"><h2 className="truncate font-serif text-lg">{product.name}</h2><p className="font-medium">{money.format(product.salePrice??product.price)}</p><div className="mt-2 flex items-center gap-2 text-xs"><Stock product={product}/><span className="truncate text-on-surface-variant">{product.sku}</span></div></button><Switch checked={product.isActive} label={`${product.name} availability`} onClick={onAvailability}/></article>}
function ProductGrid({products,selected,onSelect,onEdit}:{products:Product[];selected:Set<string>;onSelect:(id:string)=>void;onEdit:(p:Product)=>void}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map((p,i)=><article key={p.id} className="overflow-hidden rounded-2xl bg-surface-container-lowest shadow-sm"><div className="relative aspect-[4/3]"><Image src={images[i%images.length]} alt="" fill className="object-cover"/><button onClick={()=>onSelect(p.id)} aria-label={`Select ${p.name}`} className={cn("absolute left-3 top-3 grid h-11 w-11 place-items-center rounded-full bg-white",selected.has(p.id)&&"bg-secondary text-on-secondary")}><Check/></button></div><button onClick={()=>onEdit(p)} className="w-full p-4 text-left"><h2 className="font-serif text-xl">{p.name}</h2><p className="text-sm text-on-surface-variant">{p.sku} · {p.category?.name}</p><div className="mt-3 flex justify-between"><Stock product={p}/><strong>{money.format(p.price)}</strong></div></button></article>)}</div>}
function Stock({product}:{product:Product}){const low=product.stock>0&&product.stock<=(product.lowStockThreshold??5);return <span className={cn("inline-flex items-center gap-1 text-xs",product.stock===0?"text-error":low?"text-tertiary":"text-secondary")}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{product.stock===0?"Out of stock":low?`Low stock (${product.stock})`:`${product.stock} in stock`}</span>}
function Switch({checked,label,onClick}:{checked:boolean;label:string;onClick:()=>void}){return <button role="switch" aria-checked={checked} aria-label={label} onClick={onClick} className={cn("relative h-11 w-12 rounded-full after:absolute after:left-1 after:top-3 after:h-5 after:w-5 after:rounded-full after:bg-white after:transition-transform",checked?"bg-secondary after:translate-x-5":"bg-surface-dim")} />}
function Action({label,onClick,destructive,children}:{label:string;onClick:()=>void;destructive?:boolean;children:React.ReactNode}){return <button aria-label={label} title={label} onClick={onClick} className={cn("grid h-11 w-11 place-items-center rounded-full text-on-surface-variant hover:bg-surface-container [&_svg]:h-4 [&_svg]:w-4",destructive&&"hover:text-error")}>{children}</button>}
function Filters({open,setOpen,categories,category,setCategory,stock,setStock,availability,setAvailability,clear}:{open:boolean;setOpen:(v:boolean)=>void;categories:string[];category:string;setCategory:(v:string)=>void;stock:StockFilter;setStock:(v:StockFilter)=>void;availability:Availability;setAvailability:(v:Availability)=>void;clear:()=>void}){
  useEffect(()=>{
    if(!open)return;
    document.body.style.overflow="hidden";
    const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};
    window.addEventListener("keydown",onKey);
    return ()=>{document.body.style.overflow="";window.removeEventListener("keydown",onKey)};
  },[open,setOpen]);
  return <div>
    <div onClick={()=>setOpen(false)} aria-hidden={!open} className={cn("fixed inset-0 z-40 bg-on-surface/20 backdrop-blur-sm transition-opacity duration-300",open?"pointer-events-auto opacity-100":"pointer-events-none opacity-0")} />
    <aside role="dialog" aria-modal="true" aria-hidden={!open} aria-labelledby="filter-title" className={cn("fixed z-50 flex w-full flex-col bg-surface shadow-2xl transition-transform duration-300 ease-in-out","inset-x-0 bottom-0 h-auto max-h-[85svh] rounded-t-2xl md:inset-x-auto md:right-0 md:top-0 md:h-full md:w-96 md:max-h-none md:rounded-none",open?"translate-y-0 md:translate-x-0":"translate-y-full md:translate-x-full")}>
      <div className="flex items-center justify-between border-b border-outline-variant/30 px-6 py-5">
        <h2 id="filter-title" className="font-serif text-2xl text-on-surface">Filter products</h2>
        <button aria-label="Close filters" onClick={()=>setOpen(false)} className="flex h-11 w-11 items-center justify-center rounded-full text-on-surface-variant transition-colors hover:bg-surface-variant/30">
          <X className="h-5 w-5" />
        </button>
      </div>
      <div className="flex-1 space-y-6 overflow-y-auto p-6">
        <FilterSelect label="Category" value={category} onChange={setCategory} options={[["all","All categories"],...categories.map(c=>[c,c])]} />
        <FilterSelect label="Stock" value={stock} onChange={v=>setStock(v as StockFilter)} options={[["all","All stock"],["in","In stock"],["low","Low stock"],["out","Out of stock"]]} />
        <FilterSelect label="Availability" value={availability} onChange={v=>setAvailability(v as Availability)} options={[["all","All products"],["available","Available"],["hidden","Hidden"]]} />
      </div>
      <div className="flex items-center gap-3 border-t border-outline-variant/30 bg-surface-container-lowest p-6">
        <button onClick={clear} className="min-h-11 flex-1 rounded-full py-3 text-sm font-medium text-secondary transition-colors hover:bg-surface-variant/20">Clear filters</button>
        <button onClick={()=>setOpen(false)} className="min-h-11 flex-[2] rounded-full bg-primary py-3 text-sm font-medium text-on-primary shadow-md transition-colors hover:bg-primary/90">Show products</button>
      </div>
    </aside>
  </div>;
}
function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="block text-sm font-medium">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-outline-variant bg-surface px-3">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function EditDialog({product,setProduct,busy,save}:{product:Product|null;setProduct:(p:Product|null)=>void;busy:boolean;save:(p:Product)=>void}){const update=(key:"name"|"sku"|"price"|"stock",value:string)=>product&&setProduct({...product,[key]:key==="price"||key==="stock"?Number(value):value});return <Dialog open={!!product} onOpenChange={o=>!o&&setProduct(null)}><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Quick edit</DialogTitle><DialogDescription>Update core merchandising and inventory details.</DialogDescription></DialogHeader>{product&&<div className="grid gap-3"><label>Name<Input value={product.name} onChange={e=>update("name",e.target.value)}/></label><label>SKU<Input value={product.sku} onChange={e=>update("sku",e.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label>Price<Input type="number" min="0" value={product.price} onChange={e=>update("price",e.target.value)}/></label><label>Stock<Input type="number" min="0" value={product.stock} onChange={e=>update("stock",e.target.value)}/></label></div><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={product.isBestSeller??false} onChange={e=>setProduct({...product,isBestSeller:e.target.checked})}/>Bestseller</label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={product.sameDayDelivery??false} onChange={e=>setProduct({...product,sameDayDelivery:e.target.checked})}/>Same-day delivery</label></div>}<DialogFooter><Button variant="outline" onClick={()=>setProduct(null)}>Cancel</Button><Button disabled={busy||!product?.name.trim()} onClick={()=>product&&save(product)}>Save changes</Button></DialogFooter></DialogContent></Dialog>}
